/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#27272a",
        "on-primary": "#000000",
        "primary-fixed": "#e4e4e7",
        "on-surface-variant": "#a1a1aa",
        "on-surface": "#f4f4f5",
        "on-tertiary-fixed-variant": "#71717a",
        "primary-container": "#ffffff",
        "tertiary": "#f4f4f5",
        "on-primary-container": "#000000",
        "error-container": "#450a0a",
        "background": "#000000",
        "tertiary-fixed-dim": "#e4e4e7",
        "primary-fixed-dim": "#d4d4d8",
        "on-error-container": "#fca5a5",
        "surface-container-lowest": "#050507",
        "secondary-fixed": "#e4e4e7",
        "surface-container-highest": "#27272a",
        "surface-tint": "#ffffff",
        "secondary-container": "#27272a",
        "inverse-primary": "#000000",
        "secondary-fixed-dim": "#d4d4d8",
        "on-secondary-fixed": "#000000",
        "on-tertiary-container": "#000000",
        "on-background": "#f4f4f5",
        "on-secondary-fixed-variant": "#52525b",
        "surface-container-high": "#18181b",
        "surface-container-low": "#0a0a0c",
        "surface-bright": "#27272a",
        "on-primary-fixed": "#000000",
        "on-secondary": "#000000",
        "surface": "#0e0e11",
        "surface-variant": "#18181b",
        "tertiary-fixed": "#e4e4e7",
        "secondary": "#ffffff",
        "on-error": "#000000",
        "on-tertiary-fixed": "#000000",
        "primary": "#ffffff",
        "surface-dim": "#050507",
        "inverse-on-surface": "#09090b",
        "outline": "#71717a",
        "inverse-surface": "#f4f4f5",
        "on-tertiary": "#000000",
        "surface-container": "#121215",
        "on-secondary-container": "#ffffff",
        "error": "#f87171",
        "on-primary-fixed-variant": "#27272a",
        "tertiary-container": "#27272a"
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
}
